#-------------------------------------------
# CS 480 - Milestone #1
# Name	: Sang Shin
# Date	: 01/15/2014
#
# Makefile
#
CCC = gforth
SOURCE = m1.fs

all: stutest

stutest: $(SOURCE)
	$(CCC) $(SOURCE) > stutest.out
	cat stutest.out
clean:
	rm -f *.o *.out
	ls
