# -----------------------------------------------
# file		: Makefile
# author	: Sang Shin | Chris Newman
# date		: 02-20-2014
# class		: CS 480 | Milestone #4
# -----------------------------------------------

CCC = python
SOURCE = main.py

all: stutest

stutest: $(SOURCE)
	$(CCC) $(SOURCE) ptests/ptestN1
	$(CCC) $(SOURCE) ptests/ptestN2
	$(CCC) $(SOURCE) ptests/ptestN3
	$(CCC) $(SOURCE) ptests/ptestN4
	$(CCC) $(SOURCE) ptests/ptestN5
	$(CCC) $(SOURCE) ptests/ptestN6
	$(CCC) $(SOURCE) ptests/ptestN7
	$(CCC) $(SOURCE) ptests/ptestN8
	$(CCC) $(SOURCE) ptests/ptestN9
	$(CCC) $(SOURCE) ptests/ptestN10
	$(CCC) $(SOURCE) ptests/ptestN11
	$(CCC) $(SOURCE) ptests/ptestN12
	$(CCC) $(SOURCE) ptests/ptestN13
	$(CCC) $(SOURCE) ptests/ptestN14
	$(CCC) $(SOURCE) ptests/ptestN15
	$(CCC) $(SOURCE) ptests/ptestN16
	$(CCC) $(SOURCE) ptests/ptestN17
	$(CCC) $(SOURCE) ptests/ptestN18
	$(CCC) $(SOURCE) ptests/ptestN19
	$(CCC) $(SOURCE) ptests/ptestN20
	$(CCC) $(SOURCE) ptests/ptestN21
	$(CCC) $(SOURCE) ptests/ptestN22
	$(CCC) $(SOURCE) ptests/ptestN23
	$(CCC) $(SOURCE) ptests/ptestN24
	$(CCC) $(SOURCE) ptests/ptestN25
	$(CCC) $(SOURCE) ptests/ptestN26
	$(CCC) $(SOURCE) ptests/ptestN27
	$(CCC) $(SOURCE) ptests/ptestN28
	$(CCC) $(SOURCE) ptests/ptestN29
	$(CCC) $(SOURCE) ptests/ptestN30
	$(CCC) $(SOURCE) ptests/ptestN31
	$(CCC) $(SOURCE) ptests/ptestF1
	$(CCC) $(SOURCE) ptests/ptestF2
	$(CCC) $(SOURCE) ptests/ptestF3
	$(CCC) $(SOURCE) ptests/ptestF4
	$(CCC) $(SOURCE) ptests/ptestF5
	$(CCC) $(SOURCE) ptests/ptestF6
	$(CCC) $(SOURCE) ptests/ptestF7
	$(CCC) $(SOURCE) ptests/ptestF8
	$(CCC) $(SOURCE) ptests/ptestF9
	$(CCC) $(SOURCE) ptests/ptestF10
	$(CCC) $(SOURCE) ptests/ptestF11
	$(CCC) $(SOURCE) ptests/ptestF12
	$(CCC) $(SOURCE) ptests/ptestF13
	$(CCC) $(SOURCE) ptests/ptestF14
	$(CCC) $(SOURCE) ptests/ptestF15
	$(CCC) $(SOURCE) ptests/ptestF16
	$(CCC) $(SOURCE) ptests/ptestF17
	$(CCC) $(SOURCE) ptests/ptestF18
	$(CCC) $(SOURCE) ptests/ptestF19
	$(CCC) $(SOURCE) ptests/ptestF20
	$(CCC) $(SOURCE) ptests/ptestF21
	$(CCC) $(SOURCE) ptests/ptestF22
	$(CCC) $(SOURCE) ptests/ptestF23
	$(CCC) $(SOURCE) ptests/ptestF24
	$(CCC) $(SOURCE) ptests/ptestF25
	gforth ptests/ptestN1.fs -e bye
	gforth ptests/ptestN2.fs -e bye
	gforth ptests/ptestN3.fs -e bye
	gforth ptests/ptestN4.fs -e bye
	gforth ptests/ptestN5.fs -e bye
	gforth ptests/ptestN6.fs -e bye
	gforth ptests/ptestN7.fs -e bye
	gforth ptests/ptestN8.fs -e bye
	gforth ptests/ptestN9.fs -e bye
	gforth ptests/ptestN10.fs -e bye
	gforth ptests/ptestN11.fs -e bye
	gforth ptests/ptestN12.fs -e bye
	gforth ptests/ptestN13.fs -e bye
	gforth ptests/ptestN14.fs -e bye
	gforth ptests/ptestN15.fs -e bye
	gforth ptests/ptestN16.fs -e bye
	gforth ptests/ptestN17.fs -e bye
	gforth ptests/ptestN18.fs -e bye
	gforth ptests/ptestN19.fs -e bye
	gforth ptests/ptestN20.fs -e bye
	gforth ptests/ptestN21.fs -e bye
	gforth ptests/ptestN22.fs -e bye
	gforth ptests/ptestN23.fs -e bye
	gforth ptests/ptestN24.fs -e bye
	gforth ptests/ptestN25.fs -e bye
	gforth ptests/ptestN26.fs -e bye
	gforth ptests/ptestN27.fs -e bye
	gforth ptests/ptestN28.fs -e bye
	gforth ptests/ptestN29.fs -e bye
	gforth ptests/ptestN30.fs -e bye
	gforth ptests/ptestN31.fs -e bye
	gforth ptests/ptestF1.fs -e bye
	gforth ptests/ptestF2.fs -e bye
	gforth ptests/ptestF3.fs -e bye
	gforth ptests/ptestF4.fs -e bye
	gforth ptests/ptestF5.fs -e bye
	gforth ptests/ptestF6.fs -e bye
	gforth ptests/ptestF7.fs -e bye
	gforth ptests/ptestF8.fs -e bye
	gforth ptests/ptestF9.fs -e bye
	gforth ptests/ptestF10.fs -e bye
	gforth ptests/ptestF11.fs -e bye
	gforth ptests/ptestF12.fs -e bye
	gforth ptests/ptestF13.fs -e bye
	gforth ptests/ptestF14.fs -e bye
	gforth ptests/ptestF15.fs -e bye
	gforth ptests/ptestF16.fs -e bye
	gforth ptests/ptestF17.fs -e bye
	gforth ptests/ptestF18.fs -e bye
	gforth ptests/ptestF19.fs -e bye
	gforth ptests/ptestF20.fs -e bye
	gforth ptests/ptestF21.fs -e bye
	gforth ptests/ptestF22.fs -e bye
	gforth ptests/ptestF23.fs -e bye
	gforth ptests/ptestF24.fs -e bye
	gforth ptests/ptestF25.fs -e bye

clean:
	rm -f *.o *.out *.pyc
	ls
