# -----------------------------------------------
# file		: Makefile
# author	: Sang Shin | Chris Newman
# date		: 02/13/2014
# class		: CS 480 | Milestone #3
# -----------------------------------------------

CCC = python
SOURCE = main.py

all: stutest

stutest: $(SOURCE)
	$(CCC) $(SOURCE) ctest1
	$(CCC) $(SOURCE) ctest2
	$(CCC) $(SOURCE) ctest3
	$(CCC) $(SOURCE) ptests/ptest1
	$(CCC) $(SOURCE) ptests/ptest2
	$(CCC) $(SOURCE) ptests/ptest3
	$(CCC) $(SOURCE) ptests/ptest4
	$(CCC) $(SOURCE) ptests/ptest5
	$(CCC) $(SOURCE) ptests/ptest6
	$(CCC) $(SOURCE) ptests/ptest7
	$(CCC) $(SOURCE) ptests/ptest8
	$(CCC) $(SOURCE) ptests/ptest9
	$(CCC) $(SOURCE) ptests/ptest10
	$(CCC) $(SOURCE) ptests/ptest11
	$(CCC) $(SOURCE) ptests/ptest12
	$(CCC) $(SOURCE) ptests/ptest13
	$(CCC) $(SOURCE) ptests/ptest14
	$(CCC) $(SOURCE) ptests/ptest15
	$(CCC) $(SOURCE) ptests/ptest16
	$(CCC) $(SOURCE) ptests/ptest17
	$(CCC) $(SOURCE) ptests/ptest18
	$(CCC) $(SOURCE) ptests/ptest19
	$(CCC) $(SOURCE) ptests/ptest20
	$(CCC) $(SOURCE) ptests/ptest21
	$(CCC) $(SOURCE) ptests/ptest22
	$(CCC) $(SOURCE) ptests/ptest23
	$(CCC) $(SOURCE) ptests/ptest24
	$(CCC) $(SOURCE) ptests/ptest25
	$(CCC) $(SOURCE) ptests/ptest26
	$(CCC) $(SOURCE) ptests/ptest27
	$(CCC) $(SOURCE) ptests/ptest28
	$(CCC) $(SOURCE) ptests/ptest29
	$(CCC) $(SOURCE) ptests/ptest30
	$(CCC) $(SOURCE) ptests/ptest31
	$(CCC) $(SOURCE) ptests/ptest32
	$(CCC) $(SOURCE) ptests/ptest33
	$(CCC) $(SOURCE) ptests/ptest34
	$(CCC) $(SOURCE) ptests/ptest35
	$(CCC) $(SOURCE) ptests/ptest36
	$(CCC) $(SOURCE) ptests/ptest37
	$(CCC) $(SOURCE) ptests/ptest38
	$(CCC) $(SOURCE) ptests/ptest39
	$(CCC) $(SOURCE) ptests/ptest40
clean:
	rm -f *.o *.out *.pyc
	ls
